---
deployment:
 tasks:
 # where on cPanel should things be put
 - export DEPLOYPATH=/home/deployment_html/
 # copy files
 - /bin/cp -R Fonts $DEPLOYPATH
 - /bin/cp -R Images $DEPLOYPATH
 - /bin/cp -R Styles $DEPLOYPATH
 - /bin/cp about.html app.js contact.html faq.html index.html projects.html $DEPLOY_PATH
