name: Deploy internal To cPanel
on:
  workflow_dispatch: # allow manually triggering this workflow
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  Deploy-internal-page:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: "**/package-lock.json"
      - name: Install Dependencies and Generate
        run: |
          yarn install
          yarn generate

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_INTERNAL_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
